In [2]:
import numpy as np

a = np.array([1,5,7])
a1 = np.array([[1,5,7],[2,5,9]])
print(a)
print(a1)
print("print me 2nd index 3rd value",a1[1][2])
print(np.arange(10))
print(a.ndim)
print(a1.ndim)
a.shape
print(a1.shape)
len(a1)

[1 5 7]
[[1 5 7]
 [2 5 9]]
print me 2nd index 3rd value 9
[0 1 2 3 4 5 6 7 8 9]
1
2
(2, 3)


2

In [10]:
#python List

l=range(1000)

%timeit a**2

816 ns ± 41.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
l=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
for i in range(len(l)):
    for j in range(len(l[0])):
        print(l[i][j])
print(l.ndim)
print(l.shape)
l[1][2]=99     #Mutable Possible
print(l)



1
2
3
4
5
6
7
8
9
10
11
12
2
(4, 3)
[[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]
 [10 11 12]]


In [8]:
l=np.arange(1000)
%timeit l**2

1.86 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
# IF WE GIVE INNER ARRAY WITH DIFF NUMBER OF ELEMENTS THEN IT CONSIDERED AS SINGLE ROW VECTOR
l=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,]])

In [16]:
# MULTIDIMENSIONAL

ls = np.array([[[1,3,2],[2,6,3]],[[5,7,6],[3,7,2]]])
print(ls)
ls[0][1][2]
print(ls.shape)
print(ls.ndim)

[[[1 3 2]
  [2 6 3]]

 [[5 7 6]
  [3 7 2]]]
(2, 2, 3)
3


In [18]:
#using Linespace

ls=np.linspace(1,2,4)
print(ls)

[1.         1.33333333 1.66666667 2.        ]


In [19]:
# common Arrays

a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a= np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
a =np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
a=np.diag([1,2,3,4,5,6])
a.shape
a

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [29]:
# create array using random
#craete an array of the given shape and populate it with random samples from a uniform distribution over(0,1)
#divide the value (0,1) in 4 part

a=np.random.randn(4)
a

array([ 0.35175916,  0.66778133,  1.50177123, -0.24506576])

# Basic DataTypes


In [30]:
a=np.arange(10)
a.dtype
#print(type(a))

dtype('int32')

In [31]:
a= np.arange(10,dtype=float)
print(a.dtype)
print(type(a))
print(a)

float64
<class 'numpy.ndarray'>
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [33]:
d=np.array([1+2j,2+4j])  #complex data types
print(d.dtype)
d

complex128


array([1.+2.j, 2.+4.j])

In [34]:
b=np.array((True,False,True,False))
print(b.dtype)#Boolean data types

bool


In [35]:
d=np.array(['sam','john'])
print(d.dtype)

<U4


Indexing and Slicing

In [36]:
a=np.arange(10)
print(a)
print(a[1:9:2])
a[5:]=10
a

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [37]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[1:9:2]

array([1, 3, 5, 7])

In [39]:
np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [42]:
b=np.arange(5)
a[5:]=b[::-1]
b
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [43]:
b=np.arange(5)
a[5:]=0
b
a

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

4.Copies and Views

In [44]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [46]:
c = a[::3]
c

array([0, 3, 6, 9])

In [47]:
print(id(a))
print(id(b))
print(id(c))

2434693336016
2434693344560
2434693334576


In [48]:
np.may_share_memory(a,b)

True

In [49]:
np.may_share_memory(b,c)

True

In [50]:
np.may_share_memory(a,c)

True

In [51]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [52]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [53]:
a=np.arange(10)
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [55]:
print(np.may_share_memory(a,c))
print(id(type(a)))
print(id(type(c)))
c[0]=5
c

False
140707509257696
140707509257696


array([5, 2, 4, 6, 8])